import { screenShot } from "@/types/ScreenShot";

export const initialScreenshots: screenShot[] = [
  {
    id: "1",
    name: "Dashboard Design",
    url: "/placeholder.svg?height=600&width=800",
    folder: "designs",
    date: "2023-04-15",
    tags: ["ui", "dashboard"],
    trash: false,
  },
  {
    id: "2",
    name: "Login Screen",
    url: "/placeholder.svg?height=600&width=800",
    folder: "designs",
    date: "2023-04-10",
    tags: ["ui", "auth"],
    trash: false,
  },
  {
    id: "3",
    name: "API Documentation",
    url: "/placeholder.svg?height=600&width=800",
    folder: "documentation",
    date: "2023-03-28",
    tags: ["docs"],
    trash: false,
  },
  {
    id: "4",
    name: "User Profile",
    url: "/placeholder.svg?height=600&width=800",
    folder: "designs",
    date: "2023-03-25",
    tags: ["ui", "profile"],
    trash: false,
  },
  {
    id: "5",
    name: "Settings Page",
    url: "/placeholder.svg?height=600&width=800",
    folder: "designs",
    date: "2023-03-20",
    tags: ["ui", "settings"],
    trash: false,
  },
  {
    id: "6",
    name: "Error Page",
    url: "/placeholder.svg?height=600&width=800",
    folder: "designs",
    date: "2023-03-15",
    tags: ["ui", "error"],
    trash: false,
  },
  {
    id: "7",
    name: "Database Schema",
    url: "/placeholder.svg?height=600&width=800",
    folder: "documentation",
    date: "2023-03-10",
    tags: ["docs", "database"],
    trash: false,
  },
  {
    id: "8",
    name: "Mobile Navigation",
    url: "/placeholder.svg?height=600&width=800",
    folder: "designs",
    date: "2023-03-05",
    tags: ["ui", "mobile", "navigation"],
    trash: false,
  },
];
